name = "OutlierDetectionBenchmark"
uuid = "b1cdf2c5-ba0e-424d-bcbe-e7837a546c01"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
JLD = "0.12"
BenchmarkTools = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
